### ISSUE TITLE
Repository files are inappropriate

### ISSUE THREAD

**Issue by enderbas** [sunwookim05/Scanner-with-C#9]
While using GitHub like remote git service providers, developers mostly not commit to generated files like .o or .obj or .exe files. Your /inc and /src folders are sufficient. 

It's not a big deal but your repo explored in github.com/explore so I just want to give feedback to you.

Good Luck

**Comment by sunwookim05** [comment]
I'm still a student, so I didn't know what you gave me. Thanks for the feedback :)
